package com.ahmetocak.designsystem.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF7E4E7C)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFD6F9)
val onPrimaryContainerLight = Color(0xFF320935)
val secondaryLight = Color(0xFF6D586A)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFF6DBF0)
val onSecondaryContainerLight = Color(0xFF261625)
val tertiaryLight = Color(0xFF825247)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDAD2)
val onTertiaryContainerLight = Color(0xFF33110A)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF7FA)
val onBackgroundLight = Color(0xFF201A1E)
val surfaceLight = Color(0xFFFFF7FA)
val onSurfaceLight = Color(0xFF201A1E)
val surfaceVariantLight = Color(0xFFEDDEE8)
val onSurfaceVariantLight = Color(0xFF4D444B)
val outlineLight = Color(0xFF7F747C)
val outlineVariantLight = Color(0xFFD0C3CC)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF352E33)
val inverseOnSurfaceLight = Color(0xFFFAEDF4)
val inversePrimaryLight = Color(0xFFEEB4E9)

val primaryDark = Color(0xFFEEB4E9)
val onPrimaryDark = Color(0xFF4A204B)
val primaryContainerDark = Color(0xFF643663)
val onPrimaryContainerDark = Color(0xFFFFD6F9)
val secondaryDark = Color(0xFFD9BFD4)
val onSecondaryDark = Color(0xFF3C2B3B)
val secondaryContainerDark = Color(0xFF544152)
val onSecondaryContainerDark = Color(0xFFF6DBF0)
val tertiaryDark = Color(0xFFF6B8AA)
val onTertiaryDark = Color(0xFF4C261D)
val tertiaryContainerDark = Color(0xFF663B31)
val onTertiaryContainerDark = Color(0xFFFFDAD2)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF171216)
val onBackgroundDark = Color(0xFFEBDFE6)
val surfaceDark = Color(0xFF171216)
val onSurfaceDark = Color(0xFFEBDFE6)
val surfaceVariantDark = Color(0xFF4D444B)
val onSurfaceVariantDark = Color(0xFFD0C3CC)
val outlineDark = Color(0xFF998D96)
val outlineVariantDark = Color(0xFF4D444B)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEBDFE6)
val inverseOnSurfaceDark = Color(0xFF352E33)
val inversePrimaryDark = Color(0xFF7E4E7C)

val TransparentWhite = Color(0xB3FFFFFF)
val TmdbBlue = Color(0xFF0d253f)
val RatingStarColor = Color(0xFFFFD740)